SING = 0
PLUR = 1
ANIMATE = 2
NONANIMATE = 3
FIRST = 4
SECOND = 5
THIRD = 6
M = 7
F = 8
N = 9
PRONOUN_LIST = ['i','me','my','mine','you','your','yours','he','him','his','she','her','hers','we','us','our','ours','they','them','their','theirs','it','its','this','that','those','these']
NUMBER_DICT = {'i': [SING],
               'me': [SING],
               'my': [SING],
               'mine': [SING],
               'you': [SING,PLUR],
               'your': [SING,PLUR],
               'yours': [SING,PLUR],
               'he': [SING],
               'him': [SING],
               'his': [SING],
               'she': [SING],
               'her': [SING],
               'hers': [SING],
               'we': [PLUR],
               'us': [PLUR],
               'our': [PLUR],
               'ours': [PLUR],
               'they': [PLUR],
               'them': [PLUR],
               'their': [PLUR],
               'theirs': [PLUR],
               'it': [SING],
               'its': [SING],
               'this': [SING],
               'that': [SING],
               'those': [PLUR],
               'these': [PLUR]
               }
ANIMATE_DICT = {'i': [ANIMATE],
               'me': [ANIMATE],
               'my': [ANIMATE],
               'mine': [ANIMATE],
               'you': [ANIMATE],
               'your': [ANIMATE],
               'yours': [ANIMATE],
               'he': [ANIMATE],
               'him': [ANIMATE],
               'his': [ANIMATE],
               'she': [ANIMATE],
               'her': [ANIMATE],
               'hers': [ANIMATE],
               'we': [ANIMATE],
               'us': [ANIMATE],
               'our': [ANIMATE],
               'ours': [ANIMATE],
               'they': [ANIMATE,NONANIMATE],
               'them': [ANIMATE,NONANIMATE],
               'their': [ANIMATE,NONANIMATE],
               'theirs': [ANIMATE,NONANIMATE],
               'it': [NONANIMATE],
               'its': [NONANIMATE],
               'this': [NONANIMATE],
               'that': [NONANIMATE],
               'those': [NONANIMATE],
               'these': [NONANIMATE]}
PERSON_DICT = {'i': [FIRST],
               'me': [FIRST],
               'my': [FIRST],
               'mine': [FIRST],
               'you': [SECOND],
               'your': [SECOND],
               'yours': [SECOND],
               'he': [THIRD],
               'him': [THIRD],
               'his': [THIRD],
               'she': [THIRD],
               'her': [THIRD],
               'hers': [THIRD],
               'we': [FIRST],
               'us': [FIRST],
               'our': [FIRST],
               'ours': [FIRST],
               'they': [THIRD],
               'them': [THIRD],
               'their': [THIRD],
               'theirs': [THIRD],
               'it': [THIRD],
               'its': [THIRD],
               'this': [THIRD],
               'that': [THIRD],
               'those': [THIRD],
               'these': [THIRD]}
GENDER_DICT = {'i': [M,F],
               'me': [M,F],
               'my': [M,F],
               'mine': [M,F],
               'you': [M,F],
               'your': [M,F],
               'yours': [M,F],
               'he': [M],
               'him': [M],
               'his': [M],
               'she': [F],
               'her': [F],
               'hers': [F],
               'we': [M,F],
               'us': [M,F],
               'our': [M,F],
               'ours': [M,F],
               'they': [M,F,N],
               'them': [M,F,N],
               'their': [M,F,N],
               'theirs': [M,F,N],
               'it': [N],
               'its': [N],
               'this': [N],
               'that': [N],
               'those': [N],
               'these': [N]}